from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Rule:
    id: str
    title: str
    severity: str
    remediation: str


RULES = {
    rule.id: rule
    for rule in (
        Rule("resource.fetch_failed", "Resource could not be fetched", "error", "Restore the resource or remove/update every reference to it."),
        Rule("resource.timeout", "Resource request timed out", "error", "Restore timely delivery of the resource or update its references."),
        Rule("resource.tls_error", "Resource has a TLS connection error", "error", "Repair the certificate and TLS configuration for the resource host."),
        Rule("resource.redirect_loop", "Resource has a redirect loop", "error", "Replace the redirect cycle with one direct resource URL."),
        Rule("resource.http_error", "Resource returns an HTTP error", "error", "Serve a successful resource response or update its referring pages."),
        Rule("resource.redirect", "Resource redirects", "warning", "Reference the final resource URL directly."),
        Rule("resource.mime_mismatch", "Resource MIME type does not match its use", "error", "Return the expected Content-Type and resource body."),
        Rule("resource.empty", "Resource response is empty", "warning", "Serve valid content or remove the resource reference."),
        Rule("resource.oversized", "Resource exceeds the configured size threshold", "warning", "Compress, resize, split, or defer the resource."),
        Rule("resource.response_truncated", "Resource exceeded the download byte limit", "warning", "Raise the safe byte limit or reduce the resource size."),
        Rule("resource.missing_compression", "Compressible resource is not encoded", "warning", "Enable Brotli or gzip transfer compression for text-based assets."),
        Rule("resource.weak_cache", "Static resource has a short or missing cache lifetime", "warning", "Serve fingerprinted static assets with a long-lived Cache-Control max-age."),
        Rule("resource.mixed_content", "HTTPS page references an HTTP resource", "error", "Update the resource reference to HTTPS."),
        Rule("image.oversized_dimensions", "Image dimensions exceed the configured threshold", "warning", "Resize the source image and serve responsive variants sized for their display context."),
        Rule("image.invalid", "Image response cannot be decoded", "error", "Serve a valid image payload matching its declared media type."),
        Rule("resource.duplicate_payload", "Multiple resource URLs return identical content", "info", "Consolidate duplicate assets where separate URLs are unnecessary."),
        Rule("crawl.limit_reached", "Crawl stopped at a configured limit", "error", "Increase the limit or reduce crawl scope so the audit covers the whole site."),
        Rule("page.fetch_failed", "Page could not be fetched", "error", "Restore the page or remove links to it."),
        Rule("page.http_error", "Page returns an HTTP error", "error", "Restore the page or remove it from crawl entry points, internal links and sitemaps."),
        Rule("page.timeout", "Page request timed out", "error", "Restore timely server responses and investigate origin or network latency."),
        Rule("page.tls_error", "Page has a TLS connection error", "error", "Repair the certificate and TLS configuration for the page host."),
        Rule("page.redirect_loop", "Page has a redirect loop", "error", "Replace the redirect cycle with one direct destination."),
        Rule("link.http_error", "Internal link target returns an HTTP error", "error", "Restore the target or update every internal link that references it."),
        Rule("link.redirect", "Internal link target redirects", "warning", "Update internal links to point directly to the final URL."),
        Rule("link.insecure_internal", "HTTPS page links to an insecure internal URL", "warning", "Update the internal link to use the HTTPS destination directly."),
        Rule("link.internal_nofollow", "Internal links use nofollow", "info", "Remove nofollow from internal links unless crawl suppression is intentional."),
        Rule("link.text_missing", "Internal links have no descriptive text", "warning", "Add concise anchor text or useful alternative text to linked images."),
        Rule("canonical.http_error", "Canonical target returns an HTTP error", "error", "Point the canonical to a successful, indexable URL."),
        Rule("canonical.redirect", "Canonical target redirects", "error", "Point the canonical directly to its final successful URL."),
        Rule("canonical.chain", "Canonical target declares another canonical", "warning", "Use a single direct canonical target across the cluster."),
        Rule("canonical.loop", "Canonical declarations form a loop", "error", "Choose one canonical URL and point every cluster member directly to it."),
        Rule("directive.noindex_canonical_conflict", "Noindex page canonicalizes elsewhere", "warning", "Use either noindex or canonical consolidation consistently for the intended outcome."),
        Rule("directive.invalid_robots", "Robots directive contains unsupported tokens", "warning", "Correct or remove invalid robots meta or X-Robots-Tag tokens."),
        Rule("directive.conflicting_robots", "Robots directives conflict", "error", "Remove contradictory index/follow directives and declare one unambiguous policy."),
        Rule("canonical.missing", "Indexable page has no canonical declaration", "info", "Add a single canonical URL when explicit canonicalization is appropriate."),
        Rule("canonical.multiple", "Page declares multiple canonicals", "error", "Declare exactly one canonical URL in the document head."),
        Rule("canonical.invalid", "Canonical declaration is invalid", "error", "Provide one valid absolute or resolvable HTTP(S) canonical URL."),
        Rule("canonical.blocked_target", "Canonical target is blocked by robots.txt", "error", "Allow crawling of the canonical target or choose a crawlable canonical URL."),
        Rule("canonical.header_html_conflict", "HTTP and HTML canonical declarations conflict", "error", "Align canonical targets declared in the HTTP Link header and HTML document."),
        Rule("page.meta_refresh", "Page uses a meta refresh", "warning", "Replace meta refresh behavior with an appropriate HTTP redirect or normal navigation."),
        Rule("page.refresh_header", "Page uses an HTTP Refresh header", "warning", "Replace the Refresh header with an appropriate HTTP redirect."),
        Rule("structured_data.invalid_jsonld", "JSON-LD block contains invalid JSON", "error", "Correct the JSON syntax in the structured-data block."),
        Rule("structured_data.duplicate_jsonld", "Page repeats an identical JSON-LD block", "warning", "Remove duplicate structured-data script blocks while retaining one complete declaration."),
        Rule("structured_data.invalid_shape", "JSON-LD keywords have invalid value shapes", "error", "Correct invalid JSON-LD root and keyword values to conform to JSON-LD structure."),
        Rule("structured_data.missing_context", "Typed JSON-LD has no context", "warning", "Declare the vocabulary with an appropriate @context value."),
        Rule("structured_data.unresolved_fragment", "JSON-LD local identifier has no definition", "warning", "Define the referenced local @id node on the page or correct the reference."),
        Rule("structured_data.missing_required_property", "Structured data omits a property its type requires", "error", "Add the required properties so the markup is eligible for rich results."),
        Rule("structured_data.missing_recommended_property", "Structured data omits a recommended property", "info", "Add the recommended properties to improve how the result can be presented."),
        Rule("structured_data.invalid_property_value", "Structured data property has an invalid value", "warning", "Correct the property value to the format its type expects."),
        Rule("sitemap.fetch_failed", "Sitemap could not be fetched", "error", "Restore the sitemap or remove its declaration from robots.txt or the sitemap index."),
        Rule("sitemap.http_error", "Sitemap returns an HTTP error", "error", "Serve the sitemap successfully or update/remove its declaration."),
        Rule("sitemap.invalid_xml", "Sitemap XML is malformed or unsupported", "error", "Serve a valid XML urlset or sitemapindex document."),
        Rule("sitemap.duplicate_url", "Sitemap contains duplicate URLs", "warning", "List each canonical URL only once across the sitemap set."),
        Rule("sitemap.invalid_lastmod", "Sitemap lastmod value is invalid", "warning", "Use a valid W3C date or datetime in lastmod."),
        Rule("sitemap.url_limit", "Sitemap exceeds the URL protocol limit", "error", "Split the sitemap so each file contains no more than 50,000 URLs."),
        Rule("sitemap.byte_limit", "Sitemap exceeds the configured byte limit", "error", "Split or compress the sitemap within the protocol size limit."),
        Rule("sitemap.recursion_limit", "Sitemap discovery reached its configured limit", "error", "Raise the sitemap limit or remove recursive/unnecessary sitemap indexes."),
        Rule("sitemap.url_http_error", "Sitemap URL returns an HTTP error", "error", "Remove the URL from the sitemap or restore a successful canonical page."),
        Rule("sitemap.url_redirect", "Sitemap URL redirects", "warning", "Replace it with the final canonical URL."),
        Rule("sitemap.url_noindex", "Sitemap URL is noindex", "error", "Remove the URL from the sitemap or make it indexable."),
        Rule("sitemap.url_noncanonical", "Sitemap URL canonicalizes elsewhere", "warning", "List only the canonical URL in the sitemap."),
        Rule("sitemap.url_blocked", "Sitemap contains a robots-blocked URL", "error", "Allow crawling of the URL or remove it from the sitemap."),
        Rule("sitemap.page_missing", "Indexable page is absent from the sitemap", "warning", "Add the page to a sitemap, or make it non-indexable if it should not be discovered."),
        Rule("hreflang.invalid_language", "Hreflang language tag is invalid", "error", "Use x-default or a valid language tag with optional script and region subtags."),
        Rule("hreflang.duplicate_language", "Page has duplicate hreflang language entries", "error", "Declare only one alternate URL for each language/region value."),
        Rule("hreflang.missing_self", "Hreflang cluster is missing a self-reference", "warning", "Include the current canonical page in its own hreflang set."),
        Rule("hreflang.missing_return", "Hreflang alternate has no return link", "error", "Add a reciprocal hreflang reference from the alternate page."),
        Rule("hreflang.target_http_error", "Hreflang target returns an HTTP error", "error", "Point hreflang to a successful indexable page."),
        Rule("hreflang.target_redirect", "Hreflang target redirects", "error", "Point hreflang directly to the final canonical URL."),
        Rule("hreflang.target_noindex", "Hreflang target is noindex", "error", "Use an indexable alternate target or remove it from the cluster."),
        Rule("hreflang.target_noncanonical", "Hreflang target canonicalizes elsewhere", "warning", "Point hreflang to the target's canonical URL."),
        Rule("hreflang.target_blocked", "Hreflang target is blocked by robots.txt", "error", "Allow crawling of the regional target or remove the hreflang declaration."),
        Rule("external_link.fetch_failed", "External link could not be checked", "warning", "Verify the destination manually or update/remove the link."),
        Rule("external_link.http_error", "External link target returns an HTTP error", "warning", "Update or remove the external link."),
        Rule("external_link.redirect", "External link target redirects", "info", "Link directly to the final destination where practical."),
        Rule("render.unavailable", "Rendered diagnostics are unavailable", "warning", "Install the optional browser dependency and its Chromium runtime, or disable rendered diagnostics."),
        Rule("render.navigation_failed", "Page failed during browser rendering", "error", "Restore the page and its browser execution path, then rerun rendered diagnostics."),
        Rule("render.failed_requests", "Browser rendering encountered failed requests", "warning", "Restore or update failed requests that affect the rendered page."),
        Rule("render.console_errors", "Browser rendering emitted console errors", "warning", "Resolve actionable browser console errors and verify the page still renders correctly."),
        Rule("render.excessive_requests", "Rendered page makes too many network requests", "warning", "Reduce unnecessary page dependencies and consolidate requests where practical."),
        Rule("render.excessive_transfer", "Rendered page transfers too much data", "warning", "Reduce and compress page resources loaded during browser rendering."),
        Rule("render.network_inventory_truncated", "Rendered network inventory reached its safety limit", "warning", "Raise the rendered network-request limit to retain the complete waterfall for this page."),
        Rule("render.seo_signals_unavailable", "Rendered SEO declarations could not be inspected", "warning", "Resolve the browser evaluation error and rerun rendered diagnostics."),
        Rule("render.title_changed", "Page title changes after rendering", "warning", "Serve a stable, descriptive title in raw HTML and the rendered DOM."),
        Rule("render.meta_description_changed", "Meta description changes after rendering", "warning", "Serve a stable meta description in raw HTML and the rendered DOM."),
        Rule("render.canonical_changed", "Canonical declaration changes after rendering", "error", "Keep the canonical declaration stable between raw HTML and the rendered DOM."),
        Rule("render.robots_changed", "Robots directives change after rendering", "error", "Keep robots meta directives stable between raw HTML and the rendered DOM."),
        Rule("render.h1_changed", "H1 headings change after rendering", "warning", "Ensure primary headings are available and stable in raw HTML and the rendered DOM."),
        Rule("render.language_changed", "HTML language changes after rendering", "warning", "Keep the document language stable between raw HTML and the rendered DOM."),
        Rule("accessibility.critical_violations", "Rendered page has serious accessibility violations", "error", "Resolve critical and serious axe-core violations and retest the rendered page."),
        Rule("accessibility.violations", "Rendered page has accessibility violations", "warning", "Resolve axe-core accessibility violations and retest the rendered page."),
        Rule("accessibility.unavailable", "Accessibility analysis could not run", "warning", "Install axe-core, configure its script path, and rerun accessibility analysis."),
        Rule("accessibility.inventory_truncated", "Accessibility evidence reached its safety limit", "warning", "Raise the configured accessibility evidence limits to retain all violations and affected nodes."),
        Rule("architecture.deep_page", "Page exceeds the configured click depth", "warning", "Add useful internal links that bring important pages closer to the site entry point."),
        Rule("architecture.sitemap_orphan", "Sitemap page has no incoming internal links", "warning", "Link to the page from relevant indexable content, or remove it from the sitemap if it should not be discovered."),
        Rule("architecture.low_inlinks", "Page has few incoming internal links", "warning", "Add relevant internal links from useful pages to strengthen discovery and context."),
        Rule("architecture.single_dofollow_inlink", "Page has exactly one incoming dofollow internal link", "warning", "Add further relevant internal links so discovery does not depend on a single link."),
        Rule("architecture.mixed_rel_inlinks", "Page receives both nofollow and dofollow internal links", "info", "Use one consistent rel policy for internal links to the same destination."),
        Rule("architecture.no_outlinks", "Page has no outgoing internal links", "info", "Add relevant internal navigation where it helps users and crawlers continue through the site."),
        Rule("content.title_missing", "Page title is missing", "error", "Add a unique, descriptive title element."),
        Rule("content.title_too_long", "Page title exceeds the configured length", "warning", "Shorten the title while retaining its primary topic and intent."),
        Rule("content.title_too_short", "Page title is unusually short", "warning", "Write a descriptive title that communicates the page topic and intent."),
        Rule("content.duplicate_title", "Multiple pages share the same title", "warning", "Give each indexable page a distinct title that describes its unique purpose."),
        Rule("content.meta_description_missing", "Meta description is missing", "warning", "Add a useful description for the page's search snippet."),
        Rule("content.meta_description_too_long", "Meta description exceeds the configured length", "warning", "Shorten the description so its key message is less likely to be truncated."),
        Rule("content.meta_description_too_short", "Meta description is unusually short", "info", "Write a useful description that summarizes the page for search snippets."),
        Rule("content.duplicate_meta_description", "Multiple pages share the same meta description", "warning", "Write a distinct description for each indexable page."),
        Rule("content.duplicate_body", "Multiple pages have identical visible content", "error", "Consolidate duplicate pages or make each canonical page substantively distinct."),
        Rule("content.near_duplicate_body", "Multiple pages have substantially similar visible content", "warning", "Consolidate overlapping pages or add meaningful unique content."),
        Rule("content.h1_missing", "Page has no H1 heading", "warning", "Add one clear primary heading that describes the page."),
        Rule("content.multiple_h1", "Page has multiple H1 headings", "warning", "Use one primary H1 and structure subordinate headings with lower levels."),
        Rule("content.duplicate_h1", "Multiple pages share the same primary heading", "warning", "Give each indexable page a distinct primary heading."),
        Rule("content.heading_order_skipped", "Heading hierarchy skips levels", "warning", "Use sequential heading levels to communicate a coherent document outline."),
        Rule("content.thin", "Page has little visible text content", "warning", "Add useful original content that satisfies the page's search intent."),
        Rule("content.title_changed", "Page title changed since the previous run", "info", "Confirm the new title is intended and reflects the page's search intent."),
        Rule("content.meta_description_changed", "Meta description changed since the previous run", "info", "Confirm the new description is intended."),
        Rule("content.h1_changed", "Primary heading changed since the previous run", "info", "Confirm the new heading is intended."),
        Rule("content.word_count_changed", "Visible word count changed materially since the previous run", "info", "Confirm content was added or removed deliberately."),
        Rule("robots.unavailable", "robots.txt is temporarily unavailable", "error", "Restore a successful robots.txt response so crawlers can reliably determine access policy."),
        Rule("robots.byte_limit", "robots.txt exceeds the configured byte limit", "warning", "Reduce robots.txt below the supported size limit and keep directives concise."),
        Rule("robots.invalid_syntax", "robots.txt contains malformed directives", "warning", "Correct malformed robots.txt lines so crawlers interpret the intended policy."),
        Rule("robots.blocked_page", "Page is blocked by robots.txt", "error", "Allow crawling for the configured search crawler or remove the page from internal discovery and sitemaps."),
        Rule("robots.blocked_resource", "Page resource is blocked by robots.txt", "warning", "Allow crawling of resources required to render and understand indexable pages."),
        Rule("page.oversized", "HTML page exceeds the configured size threshold", "warning", "Reduce generated HTML and remove unnecessary inline markup or data."),
        Rule("page.slow_response", "Page response exceeds the configured duration", "warning", "Reduce server response time and investigate slow application or origin work."),
        Rule("page.response_truncated", "Page exceeded the download byte limit", "error", "Reduce the HTML response or raise the safe per-page byte limit."),
        Rule("page.redirect_chain", "Page uses a multi-hop redirect chain", "warning", "Redirect directly to the final canonical destination in one hop."),
        Rule("page.soft_404", "Successful response appears to be a not-found page", "error", "Return an appropriate 404 or 410 status for missing content, or restore the intended page."),
        Rule("content.viewport_missing", "Page has no viewport declaration", "warning", "Add a responsive viewport meta tag for mobile rendering."),
        Rule("content.image_alt_missing", "Page images are missing alt attributes", "warning", "Add descriptive alt text, or an explicit empty alt attribute for decorative images."),
        Rule("content.image_alt_empty", "Content images have an empty alt attribute", "warning", "Describe the image in its alt attribute, or confirm it is decorative and leave the empty alt in place."),
        Rule("document.head_missing", "HTML document has no explicit head element", "warning", "Add one explicit head element containing document metadata."),
        Rule("document.body_missing", "HTML document has no explicit body element", "warning", "Add one explicit body element containing the page content."),
        Rule("document.multiple_head", "HTML document has multiple head elements", "error", "Keep exactly one head element in the document."),
        Rule("document.multiple_body", "HTML document has multiple body elements", "error", "Keep exactly one body element in the document."),
        Rule("document.multiple_title", "HTML document has multiple title elements", "error", "Keep one descriptive title element in the document head."),
        Rule("document.multiple_meta_description", "HTML document has multiple meta descriptions", "warning", "Keep one meta description in the document head."),
        Rule("document.metadata_outside_head", "Document metadata appears outside the head", "warning", "Move title and meta description declarations into the document head."),
        Rule("image.missing_dimensions", "Page images omit explicit dimensions", "info", "Declare positive width and height attributes to reserve layout space."),
        Rule("image.missing_responsive_source", "Large image has no responsive source set", "warning", "Provide srcset candidates so browsers can download an appropriately sized image."),
        Rule("image.legacy_format", "Large image uses a legacy delivery format", "info", "Consider serving a modern WebP, AVIF, or JPEG XL variant where browser support permits."),
        Rule("language.html_missing", "Page has no HTML language declaration", "warning", "Add a valid lang attribute to the root html element."),
        Rule("language.html_invalid", "HTML language declaration is invalid", "error", "Use a valid language tag in the root html lang attribute."),
        Rule("language.content_invalid", "Content-Language header is invalid", "warning", "Use valid language tags in Content-Language or remove the header."),
        Rule("language.html_content_conflict", "HTML and HTTP language declarations conflict", "warning", "Align the html lang attribute and Content-Language response header."),
        Rule("language.html_hreflang_conflict", "HTML language conflicts with self hreflang", "warning", "Align the html lang attribute with the page's self-referencing hreflang declaration."),
        Rule("encoding.missing", "HTML document has no declared character encoding", "warning", "Declare UTF-8 in the HTTP Content-Type header or an early meta charset element."),
        Rule("encoding.invalid", "HTML document declares an invalid character encoding", "error", "Use a registered character encoding name, preferably UTF-8."),
        Rule("encoding.conflict", "HTML character encoding declarations conflict", "error", "Use one consistent character encoding in HTTP and HTML declarations."),
        Rule("encoding.meta_late", "HTML meta charset declaration appears too late", "warning", "Place the meta charset declaration entirely within the first 1024 bytes of the document."),
        Rule("social.og_title_missing", "Open Graph title is missing", "info", "Add an og:title value for shared-page previews."),
        Rule("social.og_description_missing", "Open Graph description is missing", "info", "Add an og:description value for shared-page previews."),
        Rule("social.og_image_missing", "Open Graph image is missing", "warning", "Add an absolute og:image URL for shared-page previews."),
        Rule("social.twitter_card_missing", "Twitter card declaration is missing", "info", "Add a twitter:card declaration and appropriate card metadata."),
        Rule("social.og_url_canonical_mismatch", "Open Graph URL does not match the canonical URL", "warning", "Point og:url at the same URL as the canonical so shares consolidate on one page."),
        Rule("link.redirect_source", "Page links to URLs that redirect", "warning", "Update the links on this page to point directly at their final URLs."),
        Rule("page.temporary_redirect", "Page uses a temporary redirect", "warning", "Use a 301 when the move is permanent so the destination consolidates ranking signals."),
        Rule("link.http_to_https", "Page links to the HTTP version of an HTTPS URL", "warning", "Link directly to the HTTPS URL instead of relying on the upgrade redirect."),
        Rule("url.too_long", "Page URL exceeds the configured length", "warning", "Use a concise, descriptive URL path and remove unnecessary parameters."),
        Rule("url.uppercase_path", "Page URL path contains uppercase characters", "info", "Use a consistent lowercase URL path and redirect alternate casing."),
        Rule("url.underscore_path", "Page URL path contains underscores", "info", "Prefer hyphens as word separators in new or migrated URL paths."),
        Rule("url.excessive_parameters", "Page URL has many query parameters", "warning", "Remove unnecessary parameters and canonicalize unavoidable variants."),
        Rule("url.tracking_parameters", "Crawlable page URL contains tracking parameters", "info", "Keep tracking parameters out of internal links and canonicalize to the clean URL."),
        Rule("url.repeated_segments", "Page URL repeats adjacent path segments", "warning", "Correct path-relative links or routing rules that repeat directory segments."),
    )
}


def get_rule(rule_id: str) -> Rule:
    try:
        return RULES[rule_id]
    except KeyError as exc:
        raise ValueError(f"Unknown rule ID: {rule_id}") from exc
